In [1]:
import pandas as pd
print(pd.__version__)

2.0.3


In [2]:
import numpy as np
import pandas as pd

data=pd.read_csv("housing.csv")
data.head(5)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [3]:
no_of_col=len(data.columns)
print(no_of_col)

10


In [4]:
missing_value=data.columns.isna()
print(missing_value)

[False False False False False False False False False False]


In [5]:
unique_value=data['ocean_proximity'].nunique()
count_unique_value=data['ocean_proximity'].unique()
print(unique_value)
print(count_unique_value)

5
['NEAR BAY' '<1H OCEAN' 'INLAND' 'NEAR OCEAN' 'ISLAND']


In [6]:
avg_val_median_house=data[data['ocean_proximity']=='NEAR BAY']['median_house_value'].mean()
print(avg_val_median_house)

259212.31179039303


In [7]:
avg_val_bedroom=data['total_bedrooms'].mean()
print(avg_val_bedroom)

537.8705525375618


In [8]:
data['total_bedrooms'].fillna(avg_val_bedroom, inplace=True)

In [9]:
avg_val_bedroom1=data['total_bedrooms'].mean()
print(avg_val_bedroom1)

537.8705525375617


In [236]:
islands=data[data['ocean_proximity']=='ISLAND']
print((islands))

      longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
8314    -118.32     33.35                27.0       1675.0           521.0   
8315    -118.33     33.34                52.0       2359.0           591.0   
8316    -118.32     33.33                52.0       2127.0           512.0   
8317    -118.32     33.34                52.0        996.0           264.0   
8318    -118.48     33.43                29.0        716.0           214.0   

      population  households  median_income  median_house_value  \
8314       744.0       331.0         2.1579            450000.0   
8315      1100.0       431.0         2.8333            414700.0   
8316       733.0       288.0         3.3906            300000.0   
8317       341.0       160.0         2.7361            450000.0   
8318       422.0       173.0         2.6042            287500.0   

     ocean_proximity  
8314          ISLAND  
8315          ISLAND  
8316          ISLAND  
8317          ISLAND  
8318         

In [237]:
X=islands[['housing_median_age','total_rooms','total_bedrooms']].values
print(X)
print(len(X))
print(len(X[0]))

[[  27. 1675.  521.]
 [  52. 2359.  591.]
 [  52. 2127.  512.]
 [  52.  996.  264.]
 [  29.  716.  214.]]
5
3


In [238]:
print(X.T)
print(len(X.T))
print(len(X.T[0]))

[[  27.   52.   52.   52.   29.]
 [1675. 2359. 2127.  996.  716.]
 [ 521.  591.  512.  264.  214.]]
3
5


In [239]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n=u.shape[0]
    
    result=0.0
    
    for i in range(n):
        result=result+u[i]*v[i]
        
    return result

In [240]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1]==v.shape[0]
    
    num_rows=U.shape[0]
    
    result=np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i]=vector_vector_multiplication(U[i],v)
        
    return result

In [241]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1]==V.shape[0]
    
    num_rows=U.shape[0]
    num_cols=V.shape[1]
    
    result=np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi=V[:, i]
        Uvi=matrix_vector_multiplication(U, vi)
        result[:,i]=Uvi
        
    return result

In [242]:
XTX=matrix_matrix_multiplication(X.T, X)
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [243]:
XTXs=XTX[[0,1,2]]
XTXs

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [244]:
XTX_inv=np.linalg.inv(XTXs)
print(XTX_inv)

[[ 9.19403586e-04 -3.66412216e-05  5.43072261e-05]
 [-3.66412216e-05  8.23303633e-06 -2.77534485e-05]
 [ 5.43072261e-05 -2.77534485e-05  1.00891325e-04]]


In [245]:
XTX_inv.dot(XTXs)

array([[ 1.00000000e+00, -7.67386155e-13, -2.06057393e-13],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [ 1.77635684e-15,  5.68434189e-14,  1.00000000e+00]])

In [265]:
y = np.array([950, 1300, 800, 1000, 1300])
print(y)
print(len(y))

[ 950 1300  800 1000 1300]
5


In [259]:
U=np.dot(XTX_inv, X.T)
print(U)
print(len(U))
print(len(U[0]))

[[-0.00825608 -0.00653208 -0.00232159  0.02565144  0.01204934]
 [-0.00165852  0.0011141   0.00139656 -0.00103215 -0.00110698]
 [ 0.00754365 -0.00301964 -0.00455125  0.00181685  0.00329418]]
3
5


In [266]:
w=U@y
print(w)

[23.12330961 -1.48124183  5.69922946]
